- name: Deploy to EC2 
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USERNAME }}
    key: ${{ secrets.SSH_KEY }}
    script: |
      sudo docker pull rishab10/week-18-class:latest
      sudo docker stop web-app || true
      sudo docker rm web-app || true
      sudo docker run -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} -d --name web-app -p 3005:3000 rishab10/week-18-class:latest
